# Site settings
title: Ben Reeves
author: Ben Reeves
email: bgreeves@umich.edu
url: "https://renbeeves.com"
timezone: America/Chicago
description: >-
  Software engineer, musician, designer, builder, and lifelong goofball.
  This is my personal website. Here you'll find my blog where
  I write about my hobbies, and links to other pages of mine.
show_last_updated: true

# Social
linkedin_username:   ben-reeves
github_username:     bgr360
soundcloud_username: renbeeves
#youtube_username:    UCtnKVh6J7QBbQDgrKm1yA1w # doesn't work well

# Social (for jekyll-seo-tag plugin)
social:
  name: Ben Reeves
  links:
    - https://www.linkedin.com/in/ben-reeves
    - https://github.com/bgr360
    - https://soundcloud.com/renbeeves
    - https://youtube.com/channel/UCtnKVh6J7QBbQDgrKm1yA1w

# Analytics
google_analytics: UA-72821182-3

# Posts
show_excerpts: true
date_format: "%b %-d, %Y, %l:%M %p"
date_format_abridged: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - .gitignore
  - CNAME
  - README.md
  - TODO.md
